name: Build CV
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: voioo/xelatex-action@v1.0.1
        with:
          file: cv.tex
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ./pdf/Jaival_Saija_CV.pdf
